---

- hosts: localhost
  connection: local

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      upgrade: dist
      update_cache: true
    tags:
      - install
      - core

  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/zsh-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/npm-packages.yml
    - include: tasks/aws-setup.yml

    - name: cleanup package cache
      become: true
      apt:
        autoclean: yes
      
    - name: autoremove orphan packages
      become: true
      apt:
        autoremove: yes
        purge: yes    