---

- hosts: localhost
  connection: local

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core

  tasks:
    - include: tasks/core-setup.yml
    - include: tasks/git-setup.yml

    - name: cleanup package cache
      become: true
      apt:
        autoclean: yes
      
    - name: autoremove orphan packages
      become: true
      apt:
        autoremove: yes
        purge: yes    